services:
  wordpress:
    depends_on:
      - db
    build:
      context: ./docker
      dockerfile: Dockerfile.wp
    restart: unless-stopped
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DOCKER_MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${DOCKER_MYSQL_DATABASE}
    volumes:
      - wordpress:/var/www/html
      - ./docker/php/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 

      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/languages:/var/www/html/wp-content/languages
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    networks:
      - app-wordpress-environment-network

  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    volumes:
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/languages:/var/www/html/wp-content/languages
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    networks:
      - app-wordpress-environment-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${DOCKER_WEBSERVER_PORT}:80"
    volumes:
      - wordpress:/var/www/html
      - ./docker/nginx-conf:/etc/nginx/conf.d
      
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/languages:/var/www/html/wp-content/languages
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    networks:
      - app-wordpress-environment-network

  db:
    image: mariadb:10.11.5
    restart: always
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/volumes/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      #- ./docker/mysql/dump/dumpname.sql:/docker-entrypoint-initdb.d/dumpname.sql
    ports:
      # - 3306:3306
      - "${DOCKER_EXTERNAL_MYSQL_PORT}:3306"
    networks:
      - app-wordpress-environment-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    networks:
      - app-wordpress-environment-network
    ports:
      #- 8083:80
      - "${DOCKER_PHP_MY_ADMIN_PORT}:80"
volumes:
  wordpress:
  dbdata:

networks:
  app-wordpress-environment-network:
    driver: bridge